import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { GroveConfig, Service } from './config.js';
import { resolveEnvVars, TemplateVars } from './templates.js';

export interface ServicePortMap {
  [serviceName: string]: { port: number; url: string };
}

export function buildServicePortMap(basePort: number, config: GroveConfig): ServicePortMap {
  const map: ServicePortMap = {};

  for (const service of config.services) {
    const isManaged = service.managed !== false;

    if (isManaged) {
      const port = basePort + service.port_offset;
      map[service.name] = {
        port,
        url: `http://localhost:${port}`,
      };
    } else {
      // Unmanaged: use fixed_port or 0 if not set
      const port = service.fixed_port || 0;
      map[service.name] = {
        port,
        url: service.fixed_url || `http://localhost:${port}`,
      };
    }
  }

  return map;
}

export function generateEnvFiles(worktreeDir: string, basePort: number, agentId: string, config: GroveConfig): void {
  // Step 1: Build the full service port map (managed + fixed)
  const serviceMap = buildServicePortMap(basePort, config);

  // Step 2: Group env vars by their target env_file
  const envFileMap = new Map<string, Record<string, string>>();

  for (const service of config.services) {
    // Skip services with no env_file (unmanaged services that don't need one)
    if (!service.env_file) continue;

    const isManaged = service.managed !== false;
    const servicePort = isManaged
      ? basePort + service.port_offset
      : service.fixed_port || 0;

    const vars: TemplateVars = {
      port: servicePort,
      agent_name: agentId,
      base_port: basePort,
      services: serviceMap,
    };

    const resolved = resolveEnvVars(service.env_vars, vars);

    // Accumulate vars for this env file (multiple services can share one file)
    const existing = envFileMap.get(service.env_file) || {};
    envFileMap.set(service.env_file, { ...existing, ...resolved });
  }

  // Step 3: Write each env file
  for (const [envFilePath, vars] of envFileMap) {
    const fullPath = path.join(worktreeDir, envFilePath);
    mkdirSync(path.dirname(fullPath), { recursive: true });

    const lines = [
      '# Generated by grove — do not edit manually',
      `# Agent: ${agentId}`,
      `# Created: ${new Date().toISOString()}`,
      '',
      ...Object.entries(vars).map(([key, value]) => `${key}=${value}`),
      '', // trailing newline
    ];

    writeFileSync(fullPath, lines.join('\n'));
  }
}
