import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { GroveConfig, Service } from './config.js';
import { resolveEnvVars, TemplateVars } from './templates.js';
import { computeSequentialPort } from './ports.js';
import { IsolationMap } from './profiles.js';

export interface ServicePortMap {
  [serviceName: string]: { port: number; url: string };
}

// Legacy: hash-based port map (backward compat)
export function buildServicePortMap(basePort: number, config: GroveConfig): ServicePortMap {
  const map: ServicePortMap = {};

  for (const service of config.services) {
    const isManaged = service.managed !== false;

    if (isManaged) {
      const port = basePort + service.port_offset;
      map[service.name] = {
        port,
        url: `http://localhost:${port}`,
      };
    } else {
      const port = service.fixed_port || 0;
      map[service.name] = {
        port,
        url: service.fixed_url || `http://localhost:${port}`,
      };
    }
  }

  return map;
}

// New: isolation-aware port map for sequential strategy
export function buildIsolationPortMap(
  config: GroveConfig,
  isolationMap: IsolationMap,
  agentIndex: number,
): ServicePortMap {
  const map: ServicePortMap = {};

  for (const service of config.services) {
    if (service.managed === false) {
      const port = service.fixed_port || 0;
      map[service.name] = {
        port,
        url: service.fixed_url || `http://localhost:${port}`,
      };
      continue;
    }

    const originalPort = service.original_port || (3000 + service.port_offset);
    const mode = isolationMap[service.name] ?? 'isolate';

    if (mode === 'isolate') {
      const port = computeSequentialPort(originalPort, agentIndex, config.port_step);
      map[service.name] = { port, url: `http://localhost:${port}` };
    } else {
      // Share: use original port (main branch's port)
      map[service.name] = { port: originalPort, url: `http://localhost:${originalPort}` };
    }
  }

  return map;
}

export function generateEnvFiles(worktreeDir: string, basePort: number, agentId: string, config: GroveConfig, serviceMap?: ServicePortMap): void {
  // Step 1: Build the full service port map (managed + fixed)
  const portMap = serviceMap ?? buildServicePortMap(basePort, config);

  // Step 2: Group env vars by their target env_file
  const envFileMap = new Map<string, Record<string, string>>();

  for (const service of config.services) {
    if (!service.env_file) continue;

    const servicePort = portMap[service.name]?.port ?? 0;

    const vars: TemplateVars = {
      port: servicePort,
      agent_name: agentId,
      base_port: basePort,
      services: portMap,
    };

    const resolved = resolveEnvVars(service.env_vars, vars);

    const existing = envFileMap.get(service.env_file) || {};
    envFileMap.set(service.env_file, { ...existing, ...resolved });
  }

  // Step 3: Write each env file
  for (const [envFilePath, vars] of envFileMap) {
    const fullPath = path.join(worktreeDir, envFilePath);
    mkdirSync(path.dirname(fullPath), { recursive: true });

    const lines = [
      '# Generated by grove — do not edit manually',
      `# Agent: ${agentId}`,
      `# Created: ${new Date().toISOString()}`,
      '',
      ...Object.entries(vars).map(([key, value]) => `${key}=${value}`),
      '',
    ];

    writeFileSync(fullPath, lines.join('\n'));
  }
}
