// Grove config.json schema documentation for MCP tool responses.
// Using string concatenation to avoid backtick escaping issues.

const CB = '```'; // code block fence

export const CONFIG_SCHEMA_DOCS = [
  '## Grove config.json Schema Reference',
  '',
  '### Top-level fields',
  '',
  '| Field | Type | Description |',
  '|-------|------|-------------|',
  '| version | number | Config version. Current: 3 |',
  '| services | Service[] | All services in the project (frontend, backend, database, etc.) |',
  '| discovered_ports | DiscoveredPort[] | Ports found by auto-discovery (informational) |',
  '| port_range_start | number | Starting port for hash-based strategy (default: 54000) |',
  '| port_block_size | number | Ports per agent in hash mode (default: 10) |',
  '| port_strategy | "sequential" or "hash" | How agent ports are computed. "sequential" = original_port + (agent_index * port_step). "hash" = legacy hash-based. |',
  '| port_step | number | Offset between agents in sequential mode (default: 100). Agent 1 gets +100, agent 2 gets +200, etc. |',
  '| profiles | Record<string, Profile> | Named isolation presets (e.g. "frontend-only") |',
  '| ai_command | string | Default AI CLI for grove run (default: "claude") |',
  '',
  '### Service fields',
  '',
  '| Field | Type | Required | Description |',
  '|-------|------|----------|-------------|',
  '| name | string | YES | Unique identifier (e.g. "frontend", "backend", "database") |',
  '| type | string | YES | Project type: "vite", "nextjs", "python", "supabase", "express", "custom", etc. |',
  '| dir | string | YES | Relative path from repo root (use "." for root, "backend" for subdirectory) |',
  '| start_cmd | string | YES | Command to start the service. Supports template variables: ${port}, ${agent_name}, ${services.<name>.port} |',
  '| install_cmd | string | YES | Dependency install command (e.g. "npm install", "pip install -r requirements.txt"). Empty string if none. |',
  '| port_offset | number | YES | Index position (0, 1, 2...). Used in hash-based port strategy. |',
  '| original_port | number | Recommended | The port this service uses on the main branch (e.g. 3000, 8000, 5432). CRITICAL for sequential port strategy. |',
  '| env_file | string or null | YES | Path to generated .env file relative to worktree root (e.g. ".env.local", "backend/.env"). null if no env file needed. |',
  '| env_vars | Record<string, string> | YES | Environment variables to write. Values support template variables (see below). |',
  '| managed | boolean | NO | Default true. Set false for external services (database, redis) that grove should NOT start/stop. |',
  '| fixed_port | number | NO | For unmanaged services: the fixed port they always run on (e.g. 5432 for Postgres). |',
  '| fixed_url | string | NO | For unmanaged services: the fixed URL (e.g. "http://localhost:54321"). |',
  '',
  '### Template variables (used in start_cmd and env_vars values)',
  '',
  '| Variable | Resolves to | Example |',
  '|----------|------------|---------|',
  '| ${port} | This service\'s assigned port | 3100 |',
  '| ${agent_name} | Agent identifier | "feature-auth" |',
  '| ${base_port} | Base port of the agent\'s block | 54520 |',
  '| ${services.<name>.port} | Another service\'s port | ${services.backend.port} -> 8100 |',
  '| ${services.<name>.url} | Another service\'s URL | ${services.backend.url} -> "http://localhost:8100" |',
  '',
  '### Profile fields',
  '',
  '| Field | Type | Description |',
  '|-------|------|-------------|',
  '| isolate | string[] | Service names that get new ports + new processes per agent |',
  '| share | string[] | Service names that use the main branch\'s port (no new process) |',
  '',
  '### Isolation modes explained',
  '',
  '- **isolate** (default for managed services): The service gets a NEW port (original_port + offset) and a NEW process is spawned in the worktree. Use for services where you\'re changing code.',
  '- **share**: The service uses the ORIGINAL port from the main branch. No new process is spawned. The worktree\'s env vars point to the main branch\'s running service. Use for services you\'re NOT changing.',
  '',
  '### Example: Full-stack project with Vite + Express + PostgreSQL + Redis',
  '',
  CB + 'json',
  '{',
  '  "version": 3,',
  '  "services": [',
  '    {',
  '      "name": "frontend",',
  '      "type": "vite",',
  '      "dir": ".",',
  '      "start_cmd": "npm run dev -- --port ${port}",',
  '      "install_cmd": "npm install",',
  '      "port_offset": 0,',
  '      "original_port": 5173,',
  '      "env_file": ".env.local",',
  '      "env_vars": {',
  '        "PORT": "${port}",',
  '        "VITE_API_URL": "http://localhost:${services.backend.port}",',
  '        "VITE_GROVE_AGENT": "${agent_name}"',
  '      }',
  '    },',
  '    {',
  '      "name": "backend",',
  '      "type": "express",',
  '      "dir": "server",',
  '      "start_cmd": "npm run dev",',
  '      "install_cmd": "npm install",',
  '      "port_offset": 1,',
  '      "original_port": 8000,',
  '      "env_file": "server/.env",',
  '      "env_vars": {',
  '        "PORT": "${port}",',
  '        "DATABASE_URL": "postgres://postgres:postgres@localhost:${services.database.port}/myapp",',
  '        "REDIS_URL": "redis://localhost:${services.cache.port}",',
  '        "FRONTEND_URL": "http://localhost:${services.frontend.port}",',
  '        "GROVE_AGENT": "${agent_name}"',
  '      }',
  '    },',
  '    {',
  '      "name": "database",',
  '      "type": "postgres",',
  '      "dir": ".",',
  '      "start_cmd": "",',
  '      "install_cmd": "",',
  '      "port_offset": 2,',
  '      "original_port": 5432,',
  '      "env_file": null,',
  '      "env_vars": {},',
  '      "managed": false,',
  '      "fixed_port": 5432',
  '    },',
  '    {',
  '      "name": "cache",',
  '      "type": "redis",',
  '      "dir": ".",',
  '      "start_cmd": "",',
  '      "install_cmd": "",',
  '      "port_offset": 3,',
  '      "original_port": 6379,',
  '      "env_file": null,',
  '      "env_vars": {},',
  '      "managed": false,',
  '      "fixed_port": 6379',
  '    }',
  '  ],',
  '  "discovered_ports": [],',
  '  "port_range_start": 54000,',
  '  "port_block_size": 10,',
  '  "port_strategy": "sequential",',
  '  "port_step": 100,',
  '  "profiles": {',
  '    "frontend-only": {',
  '      "isolate": ["frontend"],',
  '      "share": ["backend", "database", "cache"]',
  '    },',
  '    "full-stack": {',
  '      "isolate": ["frontend", "backend"],',
  '      "share": ["database", "cache"]',
  '    }',
  '  },',
  '  "ai_command": "claude"',
  '}',
  CB,
  '',
  '### With sequential port_step=100, this produces:',
  '',
  '| Service | Main branch | Agent 1 (+100) | Agent 2 (+200) |',
  '|---------|------------|----------------|----------------|',
  '| frontend | :5173 | :5273 | :5373 |',
  '| backend | :8000 | :8100 | :8200 |',
  '| database | :5432 (shared) | :5432 (shared) | :5432 (shared) |',
  '| cache | :6379 (shared) | :6379 (shared) | :6379 (shared) |',
  '',
  '### Common service patterns',
  '',
  '**Supabase (unmanaged):** managed=false, fixed_port=54321, fixed_url="http://localhost:54321"',
  '**Next.js:** start_cmd="npm run dev -- --port ${port}", env_file=".env.local", use NEXT_PUBLIC_ prefix for env vars',
  '**Vite:** start_cmd="npm run dev -- --port ${port}", env_file=".env.local", use VITE_ prefix for env vars',
  '**Python FastAPI:** start_cmd="uvicorn main:app --port ${port} --reload", env_file="backend/.env"',
  '**Express:** start_cmd="npm run dev", reads PORT from env_file',
  '',
  '### Tips',
  '',
  '1. Set original_port to the ACTUAL port each service uses on your main branch.',
  '2. For databases, caches, and other infrastructure: set managed=false.',
  '3. Cross-reference services using ${services.<name>.port} in env_vars.',
  '4. The env_file path is relative to the WORKTREE root, not the service dir.',
  '5. Multiple services can share the same env_file — their env_vars get merged.',
  '6. Use profiles to save common isolation patterns.',
].join('\n');
